platform :ios, '9.0'

source 'https://github.com/xcuYao/PrivatePods.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

target 'AwesomeProject' do

  pod 'RNFramework', '0.1.2'
  
  target 'AwesomeProjectTests' do
    inherit! :search_paths
    
  end

end

target 'AwesomeProject-tvOS' do
  # Pods for AwesomeProject-tvOS

  target 'AwesomeProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
