

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/xcuYao/PrivatePods.git'

target 'AwesomeProject' do
  pod 'RNFramework',            '0.1.10'
end